# -*- mode: python ; coding: utf-8 -*-
"""
PyQuest Monster Game - PyInstaller Spec File
Auto-generated by build_game.py on 2025-12-01 17:09:41
"""

block_cipher = None

a = Analysis(
    ['monster-game-gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        (r'C:\Users\awalk\Documents\Source\monster-game\heros', 'heros'),
        (r'C:\Users\awalk\Documents\Source\monster-game\monsters', 'monsters'),
        (r'C:\Users\awalk\Documents\Source\monster-game\art', 'art'),
        (r'C:\Users\awalk\Documents\Source\monster-game\sounds', 'sounds'),
        (r'C:\Users\awalk\Documents\Source\monster-game\store.yaml', '.'),
        (r'C:\Users\awalk\Documents\Source\monster-game\tavern.yaml', '.'),
        (r'C:\Users\awalk\Documents\Source\monster-game\story.yaml', '.')
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.scrolledtext',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'pygame',
        'pygame.mixer',
        'yaml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tests',
        'art_generation',
        'matplotlib',
        'numpy',
        'scipy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PyQuest-Monster-Game',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window for GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
